[package]
name = "kafka_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = "0.37.0"
tokio = { version = "1.44.2", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }
